"""Cross-language digest test: the Python ``canon``/``record_hash`` must
reproduce, byte-for-byte, the golden vectors generated by the Go implementation
(``testdata/digest_vectors.json``). This is the guarantee behind
``assay-analyzer replay`` — anyone can recompute the evidence hashes independently.

Runnable two ways:
    PYTHONPATH=analyzer python3 -m pytest analyzer/tests/test_digest.py
    PYTHONPATH=analyzer python3 analyzer/tests/test_digest.py
"""

from __future__ import annotations

import json
import pathlib
import sys

# Allow running as a plain script without installing the package.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from assay_analyzer.digest import canon, record_hash  # noqa: E402

VECTORS = pathlib.Path(__file__).resolve().parents[2] / "testdata" / "digest_vectors.json"


def _load() -> list[dict]:
    data = json.loads(VECTORS.read_text())
    assert data, "no vectors in golden file"
    return data


def test_python_digest_matches_go_golden() -> None:
    for v in _load():
        rec = v["record"]
        got_canon = canon(rec).hex()
        got_hash = record_hash(rec)
        assert got_canon == v["canon_hex"], (
            f"[{v['name']}] canon mismatch\n got={got_canon}\nwant={v['canon_hex']}"
        )
        assert got_hash == v["hash"], (
            f"[{v['name']}] hash mismatch\n got={got_hash}\nwant={v['hash']}"
        )


if __name__ == "__main__":
    vectors = _load()
    for v in vectors:
        rec = v["record"]
        assert canon(rec).hex() == v["canon_hex"], f"canon mismatch: {v['name']}"
        assert record_hash(rec) == v["hash"], f"hash mismatch: {v['name']}"
    print(f"OK: {len(vectors)} vectors — Python digest matches Go byte-for-byte")
    for v in vectors:
        print(f"  ✓ {v['name']:<28} {v['hash'][:16]}…")
