"""Community signed reference registry — Python mirror (Phase 2, the trust moat).

This module produces the SAME canonical signing bytes as internal/registry/
statement.go and VERIFIES Ed25519 signatures with a vendored, stdlib-only
implementation (RFC 8032). Verification is the buyer's critical path, so it must
work in a clean Python with NO third-party crypto dependency — consistent with
assay's "reproducible from raw bytes, minimal deps" ethos. Signing (a contributor
action) lives Go-side (`assay reference sign`); Python only needs to verify.

Cross-language pinned by testdata/registry_vectors.json (generated by Go): the
canon bytes and a real signature must verify here byte-for-byte.
"""

from __future__ import annotations

import hashlib
import struct
from typing import Any

STATEMENT_VERSION = 1
_DOMAIN_TAG = "assay-fingerprint-statement-v1"


# --- length-prefixed primitives (mirror internal/registry/statement.go) ---

def _u64(n: int) -> bytes:
    if n < 0 or n > 0xFFFFFFFFFFFFFFFF:
        raise ValueError(f"u64 out of range: {n}")
    return struct.pack(">Q", n)


def _s(value: str) -> bytes:
    b = value.encode("utf-8")
    return _u64(len(b)) + b


def canon_fingerprint(f: dict[str, Any]) -> bytes:
    return b"".join([
        _s("fingerprint"),
        _s(f.get("provider", "")),
        _s(f.get("model", "")),
        _s(f.get("model_snapshot", "")),
        _s(f.get("precision", "")),
        _s(f.get("prompt_pool_hash", "")),
        _s(f.get("sampling_params_hash", "")),
        _s(f.get("samples_digest", "")),
        _u64(int(f.get("n_samples", 0))),
        _s(f.get("collected_at", "")),
        _s(f.get("collection_method", "")),
    ])


def canon_statement(s: dict[str, Any]) -> bytes:
    """Byte-identical to registry.Canon in Go (excludes the sig field)."""
    return b"".join([
        _s(_DOMAIN_TAG),
        _u64(int(s.get("v", STATEMENT_VERSION))),
        canon_fingerprint(s.get("fingerprint", {})),
        _s(s.get("signer_id", "")),
        _s(s.get("signer_key", "")),
        _s(s.get("signed_at", "")),
        _s(s.get("expires_at", "")),
    ])


def fingerprint_id(f: dict[str, Any]) -> str:
    return hashlib.sha256(canon_fingerprint(f)).hexdigest()


def samples_digest(samples: dict[int, list[str]]) -> str:
    """Mirror of registry.SamplesDigest: order-invariant content digest."""
    h = hashlib.sha256()
    h.update(b"assay-samples-v1")
    for pid in sorted(samples):
        h.update(_u64(pid))
        comps = sorted(samples[pid])
        h.update(_u64(len(comps)))
        for c in comps:
            cb = c.encode("utf-8")
            h.update(_u64(len(cb)))
            h.update(cb)
    return h.hexdigest()


# --- vendored stdlib-only Ed25519 verify (RFC 8032) ---
# Public-domain reference implementation style; verify-only. ~50 lines, audited
# against the Go-generated test vectors. No third-party dependency.

_q = 2 ** 255 - 19
_L = 2 ** 252 + 27742317777372353535851937790883648493
_d = (-121665 * pow(121666, _q - 2, _q)) % _q
_I = pow(2, (_q - 1) // 4, _q)


def _xrecover(y: int) -> int:
    xx = (y * y - 1) * pow(_d * y * y + 1, _q - 2, _q)
    x = pow(xx, (_q + 3) // 8, _q)
    if (x * x - xx) % _q != 0:
        x = (x * _I) % _q
    if x % 2 != 0:
        x = _q - x
    return x


_By = (4 * pow(5, _q - 2, _q)) % _q
_Bx = _xrecover(_By)
_B = (_Bx % _q, _By % _q)


def _edwards_add(P, Q):
    x1, y1 = P
    x2, y2 = Q
    a = (x1 * y2 + x2 * y1) % _q
    den1 = (1 + _d * x1 * x2 * y1 * y2) % _q
    b = (y1 * y2 + x1 * x2) % _q
    den2 = (1 - _d * x1 * x2 * y1 * y2) % _q
    return (a * pow(den1, _q - 2, _q) % _q, b * pow(den2, _q - 2, _q) % _q)


def _scalarmult(P, e):
    if e == 0:
        return (0, 1)
    Q = _scalarmult(P, e // 2)
    Q = _edwards_add(Q, Q)
    if e & 1:
        Q = _edwards_add(Q, P)
    return Q


def _isoncurve(P):
    x, y = P
    return (-x * x + y * y - 1 - _d * x * x * y * y) % _q == 0


def _decodeint(s: bytes) -> int:
    return int.from_bytes(s, "little")


def _decodepoint(s: bytes):
    y = int.from_bytes(s, "little") & ((1 << 255) - 1)
    x = _xrecover(y)
    if x & 1 != (int.from_bytes(s, "little") >> 255):
        x = _q - x
    P = (x, y)
    if not _isoncurve(P):
        raise ValueError("decoding point that is not on curve")
    return P


def ed25519_verify(public_key: bytes, message: bytes, signature: bytes) -> bool:
    """RFC 8032 Ed25519 verify. public_key=32B, signature=64B. Returns bool."""
    if len(signature) != 64 or len(public_key) != 32:
        return False
    try:
        R = _decodepoint(signature[:32])
        A = _decodepoint(public_key)
    except (ValueError, Exception):  # noqa: BLE001
        return False
    S = _decodeint(signature[32:])
    if S >= _L:
        return False  # reject non-canonical S (malleability)
    h = int.from_bytes(hashlib.sha512(signature[:32] + public_key + message).digest(), "little")
    left = _scalarmult(_B, S)
    right = _edwards_add(R, _scalarmult(A, h))
    return left[0] == right[0] and left[1] == right[1]


def verify_statement(s: dict[str, Any]) -> bool:
    """Verify a statement's signature against its embedded signer_key over the
    canonical bytes. True = signature valid for that key (NOT that the key is
    trusted — that is the quorum/trust-store layer)."""
    try:
        pub = bytes.fromhex(s.get("signer_key", ""))
        sig = bytes.fromhex(s.get("sig", ""))
    except ValueError:
        return False
    if len(pub) != 32 or len(sig) != 64:
        return False
    return ed25519_verify(pub, canon_statement(s), sig)
