"""Community signed reference registry — Python mirror (Phase 2, the trust moat).

This module produces the SAME canonical signing bytes as internal/registry/
statement.go and VERIFIES Ed25519 signatures with a vendored, stdlib-only
implementation (RFC 8032). Verification is the buyer's critical path, so it must
work in a clean Python with NO third-party crypto dependency — consistent with
assay's "reproducible from raw bytes, minimal deps" ethos. Signing (a contributor
action) lives Go-side (`assay reference sign`); Python only needs to verify.

Cross-language pinned by testdata/registry_vectors.json (generated by Go): the
canon bytes and a real signature must verify here byte-for-byte.
"""

from __future__ import annotations

import hashlib
import struct
from typing import Any

STATEMENT_VERSION = 1
_DOMAIN_TAG = "assay-fingerprint-statement-v1"


# --- length-prefixed primitives (mirror internal/registry/statement.go) ---

def _u64(n: int) -> bytes:
    if n < 0 or n > 0xFFFFFFFFFFFFFFFF:
        raise ValueError(f"u64 out of range: {n}")
    return struct.pack(">Q", n)


def _s(value: str) -> bytes:
    b = value.encode("utf-8")
    return _u64(len(b)) + b


def canon_fingerprint(f: dict[str, Any]) -> bytes:
    return b"".join([
        _s("fingerprint"),
        _s(f.get("provider", "")),
        _s(f.get("model", "")),
        _s(f.get("model_snapshot", "")),
        _s(f.get("precision", "")),
        _s(f.get("prompt_pool_hash", "")),
        _s(f.get("sampling_params_hash", "")),
        _s(f.get("samples_digest", "")),
        _u64(int(f.get("n_samples", 0))),
        _s(f.get("collected_at", "")),
        _s(f.get("collection_method", "")),
    ])


def canon_statement(s: dict[str, Any]) -> bytes:
    """Byte-identical to registry.Canon in Go (excludes the sig field)."""
    return b"".join([
        _s(_DOMAIN_TAG),
        _u64(int(s.get("v", STATEMENT_VERSION))),
        canon_fingerprint(s.get("fingerprint", {})),
        _s(s.get("signer_id", "")),
        _s(s.get("signer_key", "")),
        _s(s.get("signed_at", "")),
        _s(s.get("expires_at", "")),
    ])


def fingerprint_id(f: dict[str, Any]) -> str:
    return hashlib.sha256(canon_fingerprint(f)).hexdigest()


def _normalize_completion(text: str) -> str:
    """MUST match registry.normalizeCompletion (Go) and
    model_identity.normalize_completion: NFC + strip. The signed digest binds the
    SAME normalized bytes the MMD kernel consumes, so two independent collectors
    of the same model converge on one FingerprintID (redteam blocker #3)."""
    import unicodedata
    return unicodedata.normalize("NFC", text).strip()


def samples_digest(samples: dict[int, list[str]]) -> str:
    """Order-invariant content digest over NORMALIZED completions. Mirror of
    registry.SamplesDigest (Go), byte-identical."""
    h = hashlib.sha256()
    h.update(b"assay-samples-v1")
    for pid in sorted(samples):
        h.update(_u64(pid))
        comps = sorted(_normalize_completion(c) for c in samples[pid])
        h.update(_u64(len(comps)))
        for c in comps:
            cb = c.encode("utf-8")
            h.update(_u64(len(cb)))
            h.update(cb)
    return h.hexdigest()


# --- vendored stdlib-only Ed25519 verify (RFC 8032) ---
# Public-domain reference implementation style; verify-only. ~50 lines, audited
# against the Go-generated test vectors. No third-party dependency.

_q = 2 ** 255 - 19
_L = 2 ** 252 + 27742317777372353535851937790883648493
_d = (-121665 * pow(121666, _q - 2, _q)) % _q
_I = pow(2, (_q - 1) // 4, _q)


def _xrecover(y: int) -> int:
    xx = (y * y - 1) * pow(_d * y * y + 1, _q - 2, _q)
    x = pow(xx, (_q + 3) // 8, _q)
    if (x * x - xx) % _q != 0:
        x = (x * _I) % _q
    if x % 2 != 0:
        x = _q - x
    return x


_By = (4 * pow(5, _q - 2, _q)) % _q
_Bx = _xrecover(_By)
_B = (_Bx % _q, _By % _q)


def _edwards_add(P, Q):
    x1, y1 = P
    x2, y2 = Q
    a = (x1 * y2 + x2 * y1) % _q
    den1 = (1 + _d * x1 * x2 * y1 * y2) % _q
    b = (y1 * y2 + x1 * x2) % _q
    den2 = (1 - _d * x1 * x2 * y1 * y2) % _q
    return (a * pow(den1, _q - 2, _q) % _q, b * pow(den2, _q - 2, _q) % _q)


def _scalarmult(P, e):
    if e == 0:
        return (0, 1)
    Q = _scalarmult(P, e // 2)
    Q = _edwards_add(Q, Q)
    if e & 1:
        Q = _edwards_add(Q, P)
    return Q


def _isoncurve(P):
    x, y = P
    return (-x * x + y * y - 1 - _d * x * x * y * y) % _q == 0


def _decodeint(s: bytes) -> int:
    return int.from_bytes(s, "little")


def _decodepoint(s: bytes):
    # CANONICAL decode (RFC 8032 + libsodium/Go strictness): the y-coordinate
    # carried in the low 255 bits MUST be < q. Without this check a non-canonical
    # encoding with y in [q, 2^255) decodes to a valid point here while Go's
    # crypto/ed25519 REJECTS it — a verify divergence over the identical bytes
    # (redteam blocker #1). Reject before recovering x.
    raw = int.from_bytes(s, "little")
    sign = raw >> 255
    y = raw & ((1 << 255) - 1)
    if y >= _q:
        raise ValueError("non-canonical y >= q")
    x = _xrecover(y)
    # RFC 8032: if x == 0 the sign bit must be 0 (x and -x coincide at 0).
    if x == 0 and sign == 1:
        raise ValueError("non-canonical x=0 with sign bit set")
    if (x & 1) != sign:
        x = _q - x
    P = (x, y)
    if not _isoncurve(P):
        raise ValueError("point not on curve")
    return P


def ed25519_verify(public_key: bytes, message: bytes, signature: bytes) -> bool:
    """RFC 8032 Ed25519 verify (canonical-strict, matching Go crypto/ed25519 and
    libsodium accept/reject behavior). public_key=32B, signature=64B -> bool.

    Strictness that pins it to Go (redteam blocker #1): rejects non-canonical y
    in point decoding for BOTH R and A, and rejects non-canonical S (>= L,
    malleability). The cofactorless verification equation [S]B == R + [h]A is used
    (Go's variant); both R and A are canonically decoded above."""
    if len(signature) != 64 or len(public_key) != 32:
        return False
    try:
        R = _decodepoint(signature[:32])
        A = _decodepoint(public_key)
    except ValueError:
        return False  # only the expected decode failure is swallowed (blocker minor)
    S = _decodeint(signature[32:])
    if S >= _L:
        return False  # reject non-canonical S (malleability)
    h = int.from_bytes(hashlib.sha512(signature[:32] + public_key + message).digest(), "little")
    left = _scalarmult(_B, S)
    right = _edwards_add(R, _scalarmult(A, h))
    return left[0] == right[0] and left[1] == right[1]


def verify_statement(s: dict[str, Any]) -> bool:
    """Verify a statement's signature against its embedded signer_key over the
    canonical bytes. True = signature valid for that key (NOT that the key is
    trusted — that is the quorum/trust-store layer)."""
    try:
        pub = bytes.fromhex(s.get("signer_key", ""))
        sig = bytes.fromhex(s.get("sig", ""))
    except ValueError:
        return False
    if len(pub) != 32 or len(sig) != 64:
        return False
    return ed25519_verify(pub, canon_statement(s), sig)


# --- quorum / trust-store (mirror of internal/registry/{trustroot,quorum,revocation}.go) ---

import re as _re  # noqa: E402

_RFC3339Z = _re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")


def _keyid_for_pubkey(pubkey_hex: str) -> str:
    try:
        raw = bytes.fromhex(pubkey_hex)
    except ValueError:
        return ""
    return hashlib.sha256(raw).hexdigest()[:16]


def _canon_trust_root(tr: dict[str, Any]) -> bytes:
    keys = sorted(tr.get("keys", []), key=lambda k: k.get("pubkey", ""))
    parts = [_s("assay-trust-root-v1"), _u64(int(tr.get("v", 1))),
             _s(tr.get("role", "")), _u64(int(tr.get("threshold", 0))), _u64(len(keys))]
    for k in keys:
        parts += [_s(k.get("pubkey", "")), _s(k.get("owner", "")),
                  _s(k.get("official_access", "")), _s(k.get("added_at", ""))]
    parts.append(_s(tr.get("expires", "")))
    return b"".join(parts)


def verify_trust_root(tr: dict[str, Any]) -> dict[str, dict] | None:
    """Return {pubkey: key} of VERIFIED root keys iff the root is self-attested by
    >= threshold of its own distinct keys and every keyid matches its pubkey.
    None on failure. (Trusting the root itself is out-of-band — see honest limit.)"""
    if tr.get("role") != "reference-root" or int(tr.get("threshold", 0)) < 1:
        return None
    by_pub = {}
    for k in tr.get("keys", []):
        if _keyid_for_pubkey(k.get("pubkey", "")) != k.get("keyid"):
            return None
        by_pub[k["pubkey"]] = k
    preimage = _canon_trust_root(tr)
    verified = {}
    for sg in tr.get("sigs", []):
        for pub, k in by_pub.items():
            if k["keyid"] == sg.get("keyid"):
                try:
                    if ed25519_verify(bytes.fromhex(pub), preimage, bytes.fromhex(sg.get("sig", ""))):
                        verified[pub] = k
                except ValueError:
                    pass
    return by_pub if len(verified) >= int(tr["threshold"]) else None


def evaluate_quorum(statements: list[dict], trust_root: dict[str, Any],
                    revocations: dict[str, Any] | None, now_z: str) -> dict[str, dict]:
    """Mirror of registry.EvaluateQuorum. Returns {fingerprint_id: {status, model,
    vetted, community, expired, threshold}}. status in PASS|STALE|NO_QUORUM.
    Distinctness on FULL pubkey; community keys never count toward quorum."""
    by_pub = verify_trust_root(trust_root)
    if by_pub is None:
        return {}
    threshold = int(trust_root["threshold"])
    revoked_keyids, revoked_fps = set(), set()
    if revocations:
        revoked_keyids = set(revocations.get("revoked_keyids", []))
        revoked_fps = set(revocations.get("revoked_fingerprint_ids", []))
    trusted_pub = {pub for pub, k in by_pub.items() if k["keyid"] not in revoked_keyids}

    groups: dict[str, dict] = {}
    for st in statements:
        fp = st.get("fingerprint", {})
        fp_id = fingerprint_id(fp)
        if fp_id in revoked_fps or not verify_statement(st):
            continue
        g = groups.setdefault(fp_id, {"model": fp.get("model"), "provider": fp.get("provider"),
                                      "vetted": set(), "expired": set(), "community": set(),
                                      "threshold": threshold, "fingerprint": fp})
        fresh = True
        exp = st.get("expires_at", "")
        if exp:
            if not _RFC3339Z.match(exp):
                continue
            fresh = exp > now_z  # canonical grammar makes lexical compare == time compare
        pub = st.get("signer_key", "")
        if pub in trusted_pub:
            (g["vetted"] if fresh else g["expired"]).add(pub)
        else:
            g["community"].add(pub)

    for g in groups.values():
        if len(g["vetted"]) >= threshold:
            g["status"] = "PASS"
        elif len(g["vetted"]) + len(g["expired"]) >= threshold:
            g["status"] = "STALE"
        else:
            g["status"] = "NO_QUORUM"
        for f in ("vetted", "expired", "community"):
            g[f] = sorted(g[f])
    return groups
